/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutCard: typeof import('./src/components/AboutCard.vue')['default']
    Experience: typeof import('./src/components/Experience.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Particles: typeof import('./src/components/Particles.vue')['default']
    ProfileCard: typeof import('./src/components/ProfileCard.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
    Spacer: typeof import('./src/components/Spacer.vue')['default']
  }
  export interface ComponentCustomProperties {
    AnimateOnScroll: typeof import('primevue/animateonscroll')['default']
  }
}
